### ISSUE TITLE
Docker reverse proxy together with Node.js

### ISSUE THREAD

**Issue by mklueh** [josiahdahl/docker-reverse-proxy-example#4]
Hi Josiah,

In my case I need a similar setup, but instead of an nginx webserver I´m hosting a Node.js site.

Do I need to run an additional nginx instance now in my "site docker-compose" in front of Node.js or is it somehow possible to do that without it?

This is my docker

```
version: '3'
services:
  application:
    build: .
    ports:
      - "3000:80"
    expose:
      - "80"
    restart: always
    environment:
        - VIRTUAL_HOST=application.docker-proxy.dev
        #- NGINX_HOST=application.docker-proxy.dev
        #- NGINX_PORT=80
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
#
# the glue!
#
networks:
    default:
        external:
            name: reverseproxy_default
```

I´m always getting a 502 status code and in the proxy log

>  2017/07/21 16:23:04 [error] 281#281: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: application.docker-proxy.dev, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:80/favicon.ico", host: "application.docker-proxy.dev", referrer: "http://application.docker-proxy.dev/"

I would really appreciate your help, thank you in advance.

Best regards,

Marian
